### ISSUE TITLE
Numeric Errors

### ISSUE THREAD

**Issue by YellowZeroFish** [swift-n-brutal/illuminant_estimation#1]

**Comment by swift-n-brutal** [comment]
@YellowZeroFish Is it nan from the beginning?

**Comment by YellowZeroFish** [comment]
Thanks for your reply~ 
Not from the beginning, and especially there are no 'NaN's in the first fold(when 0.txt as test fold). But when I test this fold, the angular loss is a little too large
![test](https://user-images.githubusercontent.com/37436800/54266686-d4e84d80-45b2-11e9-81d2-c137f97bedff.png)

**Comment by swift-n-brutal** [comment]
@YellowZeroFish I found two mistakes in the pre-processing scripts.
(1) https://github.com/swift-n-brutal/illuminant_estimation/blob/3e1d873a5103dc90511b5108d0cebfabeb63f7fb/get_locs_gs568.py#L48 I used both training and test datasets to get all locations without zero values for convenience. However, in the training dataset the image is randomly flipped, which results in misaligned coordinates. For a quick fix, you may add the following `ds_train._transformer = None` after this line.
(2) I used the original matlab code from the author of the dataset to mask out the checker board.  If you look at their dataset carefully, you will find that this line https://github.com/swift-n-brutal/illuminant_estimation/blob/3e1d873a5103dc90511b5108d0cebfabeb63f7fb/data/process_gs568.m#L42 should be `if id >= 87`. 
I will commit a fix later when the whole verification of pre-processing is done.
