### ISSUE TITLE
Impossible to generate locations on new dataset

### ISSUE THREAD

**Issue by TheZino** [swift-n-brutal/illuminant_estimation#3]
Hello,
I'm trying to use the model with the pretrained weights on a different dataset from the gs568.
I'm following your instructions but, after generating the binaries from the dataset, the code for the generation of the locs stops with error

> Traceback (most recent call last):
  File "get_locs_gs568.py", line 72, in <module>
    main()
  File "get_locs_gs568.py", line 67, in main
    get_all_locs(ds_train, psize, stride, save_dir)
  File "get_locs_gs568.py", line 13, in get_all_locs
    shape = ds.get_shape(i)
  File "/home/zino/Projects/AWB/Deep_specialized_v2/gs568_dataset.py", line 139, in get_shape
    return self._data[idx].shape
TypeError: 'NoneType' object is not subscriptable

Seems like the _data attribute is set to None so it's impossible to obtain the shape information for the generation of the loc files.
I've try to figure out how to solve the problem but I cannot find any solution.

Thank you in advance.

**Comment by swift-n-brutal** [comment]
Hi @TheZino,
A quick fix is just swapping the places of [line 9](https://github.com/swift-n-brutal/illuminant_estimation/blob/ec9b6cb4608167d351aa6b2f51f3779293f025f1/get_locs_gs568.py#L9) and 10, if cache=True for GS568Dataset. The _data is loaded when it is actually used in order to reduce the memory usage in multiprocessing mode.

**Comment by TheZino** [comment]
Thank you very much, this fixed the data generation!

In general for data preprocessing, it's better to use the cache=False version?

**Comment by swift-n-brutal** [comment]
If your program only loads each image once, setting cache=False is OK. Kindlly note that the previous quick fix doesn't solve the problem completely. I will update a fix later. If your program needs to repeatedly crop small patches from large images (like what are in the GS568 dataset), I suggest you to set cache=True.
